/** Auto-generated by scripts/write-portal-config.js - do not edit by hand. */
window.BROCHURE_SAAS = {
  supabaseUrl: "https://phftvaptlqibllkqcduf.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZnR2YXB0bHFpYmxsa3FjZHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MDU5NDcsImV4cCI6MjA5ODM4MTk0N30.1iAlLKByQiuk7Vin_nF99JaOrsoWZEzxdwhSDM70PR8",
  // Same-origin Netlify/Express SaaS API (no Edge Function CORS)
  functionsBase: "/api/saas",
  publicBaseUrl: "http://localhost:3000",
};
